import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AppWalletProvider } from "@/context/AppWalletProvider";
import { AppBar } from "@/components/AppBar";
import { BackGround } from "@/components/BackGround";
import { ReactQueryClientProvider } from "@/context/QueryClientProvider";
const poppins = Poppins({ weight: "600", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <AppWalletProvider>
          <body
            className={`${poppins.className} relative min-h-screen`}
            style={{ margin: 0, padding: 0 }}
          >
            <BackGround />
            <div className="relative z-10 min-h-screen">
              <AppBar />

              {children}
            </div>
          </body>
        </AppWalletProvider>
      </html>
    </ReactQueryClientProvider>
  );
}
